<?php
//var_dump($this);

$action=$this->getAction();

print($action[1]);

?>


<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/style.css" media="all">
    <title>Document</title>
</head>
<body>
<h1>This is from header</h1>
<nav>
    <ul>
        <li><a href="/home/index" <?php echo ($action=="index" ? "class=activeClass" : "") ?>>Home</a></li>
        <li><a href="/home/aboutUs">About us</a></li>
    </ul>
</nav>

